<?php

/**
 * @file
 * EDW Paragraphs Base module.
 */

use Drupal\paragraphs\Entity\Paragraph;

/**
 * Implements hook_preprocess_page().
 */
function edw_paragraphs_banner_preprocess_page(&$variables) {
  if ($variables['node']->hasField('field_paragraphs')) {
    $node = $variables['node'];

    foreach ($node->field_paragraphs->getValue() as $value) {
      $paragraph = Paragraph::load($value['target_id']);

      if (!($paragraph->getType() == 'edw_banner')) {
        continue;
      }

      unset($variables['page']['hero']);
    }
  }
}
