<?php

/**
 * @file
 * EDW Paragraphs Banner module.
 */

/**
 * Implements hook_preprocess_paragraph__edw_banner().
 */
function edw_paragraphs_banner_preprocess_paragraph__edw_banner(&$variables) {
  /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $variables['paragraph'];
  if ($paragraph->hasField('field_full_width')
    && !$paragraph->get('field_full_width')->isEmpty()) {
    $variables['full_width'] = (bool) $paragraph->get('field_full_width')->value;
  }
}
