<?php

/**
 * @file
 * EDW Paragraphs module.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;

/**
 * Implements hook_entity_base_field_info().
 */
function edw_paragraphs_entity_base_field_info(EntityTypeInterface $entity_type): array {
  $fields = [];

  if ($entity_type->id() !== 'paragraph') {
    return $fields;
  }

  $fields['edw_paragraphs_variant'] = BaseFieldDefinition::create('string')
    ->setLabel(t('Variant'))
    ->setRequired(FALSE)
    ->setTranslatable(FALSE)
    ->setRevisionable(TRUE)
    ->setSetting('max_length', 255)
    ->setDisplayConfigurable('form', FALSE)
    ->setDisplayConfigurable('view', FALSE);

  return $fields;
}
