<?php

/**
 * @file
 * EDW Paragraphs Accordion module.
 */

/**
 * Implements hook_preprocess_paragraph__edw_accordion().
 */
function edw_paragraphs_accordion_preprocess_paragraph__edw_accordion(&$variables) {
  $builder = \Drupal::entityTypeManager()->getViewBuilder('paragraph');
  $variables['identifier'] = 'paragraph--accordion-' . $variables['paragraph']->id();
  $variables['items'] = [];

  /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $variables['paragraph'];
  if (!$paragraph->hasField('field_paragraphs')) {
    return;
  }
  /** @var \Drupal\entity_reference_revisions\Plugin\Field\FieldType\EntityReferenceRevisionsItem $field_item */
  foreach ($paragraph->get('field_paragraphs') as $field_item) {
    /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
    $paragraph = \Drupal::service('entity.repository')->getTranslationFromContext($field_item->entity);
    $variables['items'][] = [
      'title' => $builder->viewField($paragraph->get('field_title')),
      'body' => $builder->viewField($paragraph->get('field_body')),
    ];
  }
}
