<?php

/**
 * @file
 * Basic module file for EDW Daily Schedule module.
 */

use Drupal\paragraphs\Entity\Paragraph;

/**
 * Implements hook_ENTITY_TYPE_presave()
 */
function edw_event_daily_schedule_paragraph_presave(Paragraph $entity) {
  /** @var \Drupal\edw_event_daily_schedule\Services\ScheduleService $scheduleService */
  $scheduleService = \Drupal::service('edw_event_daily_schedule.schedule.service');
  if ($entity->bundle() == 'edw_daily_schedule_item') {
    /** @var \Drupal\paragraphs\Entity\Paragraph $parent */
    $parent = $entity->getParentEntity();
    $scheduleItems = $scheduleService->getScheduleItems($parent);
    $status = (!empty($scheduleItems) && !$parent->isPublished());
    $scheduleService->updateParagraphStatus($parent, $status);
  }
  if ($entity->bundle() == 'edw_daily_schedule') {
    $scheduleItems = $scheduleService->getScheduleItems($entity);
    $status = (!empty($scheduleItems) && !$entity->isPublished());
    $scheduleService->updateParagraphStatus($entity, $status);
  }
}

