<?php

/**
 * @file
 * EDW Paragraphs Carousel module.
 */

use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function edw_paragraphs_carousel_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle) {
  // Add constraint to the 'items' field of the Carousel paragraph.
  if ($entity_type->id() === 'paragraph' && $bundle === 'edw_carousel') {
    if (isset($fields['field_paragraphs'])) {
      $fields['field_paragraphs']->addConstraint('CarouselItemsCardinality', []);
    }
  }
}
