<?php

/**
 * @file
 * EDW Paragraphs Heading module.
 */

/**
 * Implements hook_preprocess_paragraph__edw_heading().
 */
function edw_paragraphs_heading_preprocess_paragraph__edw_heading(&$variables) {
  $variables['items'] = [];

  /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $variables['paragraph'];
  if ($paragraph->hasField('field_heading_level')
    && !$paragraph->get('field_heading_level')->isEmpty()) {
    $variables['content']['heading_level'] = $paragraph->get('field_heading_level')->value;
  }
}
