<?php

/**
 * @file
 * Basic module file for EDW event groups module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\node\NodeInterface;
use Drupal\group\Entity\GroupInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function edw_event_groups_form_entity_clone_form_alter(&$form, FormStateInterface $formState, $formId) {
  /** @var \Drupal\node\Entity\Node $node */
  $node = \Drupal::routeMatch()->getParameter('node');
  if (!$node instanceof NodeInterface || $node->bundle() != 'event') {
    return;
  }

  $form['meeting_groups'] = [
    '#type' => 'checkbox',
    '#title' => t('Clone meeting access groups.'),
    '#description' => t('If the cloned entity should be saved with all the access groups.'),
    '#default_value' => TRUE,
  ];
}


/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function edw_event_groups_group_delete(GroupInterface $group) {
  // If a group is deleted cleanup its relationships.
  $nodeStorage = \Drupal::entityTypeManager()->getStorage('node');
  $nids = $nodeStorage->getQuery()
    ->accessCheck(FALSE)
    ->condition('type', 'event_section')
    ->condition('field_groups.target_id', $group->id())
    ->execute();

  foreach ($nids as $nid) {
    /** @var \Drupal\node\NodeInterface $section */
    $section = $nodeStorage->load($nid);
    $groups = $section->get('field_groups')->getValue();
    $targetIds = array_column($groups, 'target_id');
    $index = array_search($group->id(), $targetIds);
    unset($groups[$index]);
    $section->set('field_groups', $groups);
    $section->save();
  }
}

/**
 * Implements hook_preprocess_HOOK() for views-view-field.html.twig.
 */
function edw_event_groups_preprocess_views_view_field(&$variables) {
  /** @var \Drupal\views\ViewExecutable $view */
  $view = $variables['view'];
  if ($view->id() != 'meeting_groups' || $view->current_display != 'access_groups') {
    return;
  }

  /** @var \Drupal\views\ResultRow $row */
  $row = $variables['row'];
  /** @var \Drupal\views\Plugin\views\field\EntityOperations $field */
  $field = $variables['field'];
  $renderer = \Drupal::service('renderer');
  /* @phpstan-ignore-next-line */
  if ($field->field != 'operations' || empty($row->_entity)) {
    return;
  }

  $build = $field->render($row);
  $links = $build['#links'];
  $newLinks = [$links['members'], $links['edit']];

  // Add remove group from section link.
  $removeGroup = $links['delete'];
  $url = Url::fromRoute('edw_event_groups.remove_group_from_section');
  $url->setRouteParameter('section', $row->_relationship_entities['reverse__node__field_groups']->id());
  $url->setRouteParameter('group', $row->_entity->id());
  $removeGroup['url'] = $url;
  $removeGroup['title'] = t('Remove group from section');
  $newLinks[] = $removeGroup;
  $build['#links'] = $newLinks;
  $variables['output'] = $renderer->render($build);
}
