<?php

/**
 * @file
 * EDW Paragraphs Text with Media module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_field_widget_single_element_WIDGET_TYPE_form_alter().
 */
function edw_paragraphs_media_field_widget_single_element_edw_paragraphs_variants_form_alter(array &$element, FormStateInterface $form_state, array $context) {
  if ($element['#paragraph_type'] == 'edw_text_with_media') {
    // Rename the 'Default' variant to 'Horizontal'.
    $element['variant']['#options']['default'] = t('Horizontal');
  }
}

/**
 * Implements hook_preprocess_paragraph__edw_text_with_media().
 */
function edw_paragraphs_media_preprocess_paragraph__edw_text_with_media(&$variables) {
  /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $variables['paragraph'];

  if ($paragraph->hasField('field_grid_layout')) {
    $variables['grid_layout'] = (string) $paragraph->get('field_grid_layout')->value;
  }

  if ($paragraph->hasField('field_media_position')) {
    $variables['variant'] = (string) $paragraph->get('field_media_position')->value;
  }

  if ($paragraph->get('edw_paragraphs_variant')->isEmpty()) {
    $variables['pattern'] = 'text_with_media';
    return;
  }
  if (\Drupal::moduleHandler()->moduleExists('ui_patterns_library')) {
    $variant = $paragraph->get('edw_paragraphs_variant')->value;
    $variables['pattern'] = ($variant != 'default') ? 'text_with_media_' . $variant : 'text_with_media';
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function edw_paragraphs_media_theme_suggestions_paragraph_alter(array &$suggestions, array $variables): void {
  /** @var \Drupal\paragraphs\ParagraphInterface $paragraph */
  $paragraph = $variables['elements']['#paragraph'];

  if ($paragraph->bundle() === 'edw_text_with_media' && !$paragraph->get('edw_paragraphs_variant')->isEmpty()) {
    $variant = $paragraph->get('edw_paragraphs_variant')->value;
    $suggestions[] = 'paragraph__' . $paragraph->bundle() . '__variant_' . $variant;
  }
}
